set -e
useradd -d /home/klassen/lehrer -c "lehrer" -m -g cdrom,plugdev,sambashare -s /bin/bash lehrer && echo lehrer:"rSKojMdWEZ" | chpasswd
useradd -d /home/klassen/seminar -c "seminar" -m -g cdrom,plugdev,sambashare -s /bin/bash seminar && echo seminar:"LksHiVocFz" | chpasswd
useradd -d /home/klassen/k1am -c "1am" -m -g cdrom,plugdev,sambashare -s /bin/bash 1am && echo 1am:"1am#165=FRH," | chpasswd
useradd -d /home/klassen/k1bm -c "1bm" -m -g cdrom,plugdev,sambashare -s /bin/bash 1bm && echo 1bm:"1bm=365)DRE-" | chpasswd
useradd -d /home/klassen/k1cm -c "1cm" -m -g cdrom,plugdev,sambashare -s /bin/bash 1cm && echo 1cm:"1cm,379&GRM%" | chpasswd
useradd -d /home/klassen/k2am -c "2am" -m -g cdrom,plugdev,sambashare -s /bin/bash 2am && echo 2am:"2am!359&TMP)" | chpasswd
useradd -d /home/klassen/k2bm -c "2bm" -m -g cdrom,plugdev,sambashare -s /bin/bash 2bm && echo 2bm:"2bm=376%WIT#" | chpasswd
useradd -d /home/klassen/k2cm -c "2cm" -m -g cdrom,plugdev,sambashare -s /bin/bash 2cm && echo 2cm:"2cm!275&PCH_" | chpasswd
useradd -d /home/klassen/k3am -c "3am" -m -g cdrom,plugdev,sambashare -s /bin/bash 3am && echo 3am:"3am.375-ZOI." | chpasswd
useradd -d /home/klassen/k3bm -c "3bm" -m -g cdrom,plugdev,sambashare -s /bin/bash 3bm && echo 3bm:"3bm%361^KAM!" | chpasswd
useradd -d /home/klassen/k3cm -c "3cm" -m -g cdrom,plugdev,sambashare -s /bin/bash 3cm && echo 3cm:"3cm%377^PRS." | chpasswd
useradd -d /home/klassen/k4am -c "4am" -m -g cdrom,plugdev,sambashare -s /bin/bash 4am && echo 4am:"4am_154^MAR_" | chpasswd
useradd -d /home/klassen/k4bm -c "4bm" -m -g cdrom,plugdev,sambashare -s /bin/bash 4bm && echo 4bm:"4bm.263&GRI#" | chpasswd
useradd -d /home/klassen/k4cm -c "4cm" -m -g cdrom,plugdev,sambashare -s /bin/bash 4cm && echo 4cm:"4cm=279^BUG-" | chpasswd
useradd -d /home/klassen/k5am -c "5am" -m -g cdrom,plugdev,sambashare -s /bin/bash 5am && echo 5am:"5am&156.PLE," | chpasswd
useradd -d /home/klassen/k5bm -c "5bm" -m -g cdrom,plugdev,sambashare -s /bin/bash 5bm && echo 5bm:"5bm#160%STW-" | chpasswd
useradd -d /home/klassen/k5cm -c "5cm" -m -g cdrom,plugdev,sambashare -s /bin/bash 5cm && echo 5cm:"5cm-354%JEN#" | chpasswd
useradd -d /home/klassen/k1af -c "1af" -m -g cdrom,plugdev,sambashare -s /bin/bash 1af && echo 1af:"1af&372(GFO^" | chpasswd
useradd -d /home/klassen/k1bf -c "1bf" -m -g cdrom,plugdev,sambashare -s /bin/bash 1bf && echo 1bf:"1bf!272_VOL&" | chpasswd
useradd -d /home/klassen/k1cf -c "1cf" -m -g cdrom,plugdev,sambashare -s /bin/bash 1cf && echo 1cf:"1cf_209&KEG#" | chpasswd
useradd -d /home/klassen/k2af -c "2af" -m -g cdrom,plugdev,sambashare -s /bin/bash 2af && echo 2af:"2af&357,BOG%" | chpasswd
useradd -d /home/klassen/k2bf -c "2bf" -m -g cdrom,plugdev,sambashare -s /bin/bash 2bf && echo 2bf:"2bf^219.STE^" | chpasswd
useradd -d /home/klassen/k3afi -c "3afi" -m -g cdrom,plugdev,sambashare -s /bin/bash 3afi && echo 3afi:"3afi_356,HIT^" | chpasswd
useradd -d /home/klassen/k3bfn -c "3bfn" -m -g cdrom,plugdev,sambashare -s /bin/bash 3bfn && echo 3bfn:"3bfn!277_BAA(" | chpasswd
useradd -d /home/klassen/k4afi -c "4afi" -m -g cdrom,plugdev,sambashare -s /bin/bash 4afi && echo 4afi:"4afi%275/279#OPP." | chpasswd
useradd -d /home/klassen/k4bfn -c "4bfn" -m -g cdrom,plugdev,sambashare -s /bin/bash 4bfn && echo 4bfn:"4bfn,217(CER(" | chpasswd
useradd -d /home/klassen/k1ai -c "1ai" -m -g cdrom,plugdev,sambashare -s /bin/bash 1ai && echo 1ai:"1ai.254,KLE#" | chpasswd
useradd -d /home/klassen/k1bi -c "1bi" -m -g cdrom,plugdev,sambashare -s /bin/bash 1bi && echo 1bi:"1bi,371)HOL&" | chpasswd
useradd -d /home/klassen/k1ci -c "1ci" -m -g cdrom,plugdev,sambashare -s /bin/bash 1ci && echo 1ci:"1ci%265&JAV&" | chpasswd
useradd -d /home/klassen/k2ai -c "2ai" -m -g cdrom,plugdev,sambashare -s /bin/bash 2ai && echo 2ai:"2ai.378%BAY&" | chpasswd
useradd -d /home/klassen/k2bi -c "2bi" -m -g cdrom,plugdev,sambashare -s /bin/bash 2bi && echo 2bi:"2bi%363&KUS)" | chpasswd
useradd -d /home/klassen/k2ci -c "2ci" -m -g cdrom,plugdev,sambashare -s /bin/bash 2ci && echo 2ci:"2ci#271_NIC%" | chpasswd
useradd -d /home/klassen/k3ai -c "3ai" -m -g cdrom,plugdev,sambashare -s /bin/bash 3ai && echo 3ai:"3ai&260(BUC#" | chpasswd
useradd -d /home/klassen/k3bi -c "3bi" -m -g cdrom,plugdev,sambashare -s /bin/bash 3bi && echo 3bi:"3bi(360,BSB&" | chpasswd
useradd -d /home/klassen/k3ci -c "3ci" -m -g cdrom,plugdev,sambashare -s /bin/bash 3ci && echo 3ci:"3ci%225^BRE)" | chpasswd
useradd -d /home/klassen/k4ai -c "4ai" -m -g cdrom,plugdev,sambashare -s /bin/bash 4ai && echo 4ai:"4ai%261%DAZ(" | chpasswd
useradd -d /home/klassen/k4bi -c "4bi" -m -g cdrom,plugdev,sambashare -s /bin/bash 4bi && echo 4bi:"4bi.257^OLI#" | chpasswd
useradd -d /home/klassen/k4cn -c "4cn" -m -g cdrom,plugdev,sambashare -s /bin/bash 4cn && echo 4cn:"4cn%276=SDO-" | chpasswd
useradd -d /home/klassen/k5ax -c "5ax" -m -g cdrom,plugdev,sambashare -s /bin/bash 5ax && echo 5ax:"5ax,278)FIN." | chpasswd
useradd -d /home/klassen/k5bi -c "5bi" -m -g cdrom,plugdev,sambashare -s /bin/bash 5bi && echo 5bi:"5bi_256^NUS#" | chpasswd
useradd -d /home/klassen/k5cn -c "5cn" -m -g cdrom,plugdev,sambashare -s /bin/bash 5cn && echo 5cn:"5cn,259(SLT&" | chpasswd
useradd -d /home/klassen/none -c "none" -m -g cdrom,plugdev,sambashare -s /bin/bash none && echo none:"none(None^None!" | chpasswd
useradd -d /home/klassen/none -c "none" -m -g cdrom,plugdev,sambashare -s /bin/bash none && echo none:"none^None=None^" | chpasswd
