set -x
userdel lehrer && rm -rf /home/klassen/klehrer
userdel seminar && rm -rf /home/klassen/kseminar
userdel 1am && rm -rf /home/klassen/k1am
userdel 1bm && rm -rf /home/klassen/k1bm
userdel 1cm && rm -rf /home/klassen/k1cm
userdel 2am && rm -rf /home/klassen/k2am
userdel 2bm && rm -rf /home/klassen/k2bm
userdel 2cm && rm -rf /home/klassen/k2cm
userdel 3am && rm -rf /home/klassen/k3am
userdel 3bm && rm -rf /home/klassen/k3bm
userdel 3cm && rm -rf /home/klassen/k3cm
userdel 4am && rm -rf /home/klassen/k4am
userdel 4bm && rm -rf /home/klassen/k4bm
userdel 4cm && rm -rf /home/klassen/k4cm
userdel 5am && rm -rf /home/klassen/k5am
userdel 5bm && rm -rf /home/klassen/k5bm
userdel 5cm && rm -rf /home/klassen/k5cm
userdel 1af && rm -rf /home/klassen/k1af
userdel 1bf && rm -rf /home/klassen/k1bf
userdel 1cf && rm -rf /home/klassen/k1cf
userdel 2af && rm -rf /home/klassen/k2af
userdel 2bf && rm -rf /home/klassen/k2bf
userdel 3afi && rm -rf /home/klassen/k3afi
userdel 3bfn && rm -rf /home/klassen/k3bfn
userdel 4afi && rm -rf /home/klassen/k4afi
userdel 4bfn && rm -rf /home/klassen/k4bfn
userdel 1ai && rm -rf /home/klassen/k1ai
userdel 1bi && rm -rf /home/klassen/k1bi
userdel 1ci && rm -rf /home/klassen/k1ci
userdel 2ai && rm -rf /home/klassen/k2ai
userdel 2bi && rm -rf /home/klassen/k2bi
userdel 2ci && rm -rf /home/klassen/k2ci
userdel 3ai && rm -rf /home/klassen/k3ai
userdel 3bi && rm -rf /home/klassen/k3bi
userdel 3ci && rm -rf /home/klassen/k3ci
userdel 4ai && rm -rf /home/klassen/k4ai
userdel 4bi && rm -rf /home/klassen/k4bi
userdel 4cn && rm -rf /home/klassen/k4cn
userdel 5ax && rm -rf /home/klassen/k5ax
userdel 5bi && rm -rf /home/klassen/k5bi
userdel 5cn && rm -rf /home/klassen/k5cn
userdel none && rm -rf /home/klassen/knone
userdel none && rm -rf /home/klassen/knone
